# apt-get update
# apt-get install curl -y
# apt-get install systemd -y
# curl -sfL https://get.k3s.io | sh -
# # Check for Ready node,
# takes maybe 30 seconds
# k3s kubectl get node
version: '3.1'

services:
  k3s:
    image: ubuntu:20.10
    restart: unless-stopped
    volumes:
      - ./app:/home/app
    command: sh -c "/home/app/entrypoint.sh"
