version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq/
      - ./data/rabbitmq/logs:/var/log/rbbitmq/
    env_file:
      - .env
    ports:
      - 45672:5672
      - 55672:15672
