version: '3.7'

services:
  db:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 58080:8080