version: '3.1'

services:
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 58080:8080
