version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 58080:8080
