version: '3.1'

services:
  redis:
    image: redis:alpine3.12
    container_name: redis
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    # command: redis-server --requirepass redis123
